### ISSUE TITLE
Plasma customization tool

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#25]
Plasma customization tool in OM Welcome that allows people to quickly get to something they feel at home in, e.g. "Act like [*] OpenMandriva [ ] Windows [ ] MacOS" (where OpenMandriva is what we think is best, Windows does things like double-clicks, MacOS does stuff like global menu bar on top of screen)

**Comment by benbullard79** [comment]
We have double click enabled by default in OM Lx 4.0. It is one of the first things I change, that and screen locker.

Anyway I wish we would do the sensible thing and have single click by default. (Sensible to me anyway.)

**Comment by tpgxyz** [comment]
I think this is done thanks to @berolinux as https://github.com/OpenMandrivaSoftware/om-feeling-like was released
