### ISSUE TITLE
Replace dbus with dbus-broker

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#34]
Replace dbus with dbus-broker
https://github.com/bus1/dbus-broker

**Comment by tpgxyz** [comment]
Finally i've managed to adapt dbus package to dbus-broker. Testing in progress.

How to test:
1. add these medias to your dnf config:
http://abf-downloads.openmandriva.org/cooker/container/715151/x86_64/main/release/
http://abf-downloads.openmandriva.org/cooker/container/715131/x86_64/main/release/
2. run `dnf upgrade --refresh`
3. observe logs for errors, warnings
4. try to run various applications

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/cooker-dbus-broker-available-for-testing/3427/1

**Comment by tpgxyz** [comment]
This is done for cooker.
