### ISSUE TITLE
Let's take /OpenMandrivaLx/issues down since only one person is using it.

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#35]
# Issue Report #
Since only one person is using this we should take it down to avoid confusion and miscommunication. We desperately need to get everyone communicating in the same place for the good of the distro.

### What is the issue type? ###

Common sense.
...
BUG_REPORT_URL="https://github.com/OpenMandrivaAssociation/OpenMandrivaLx/issues"
```

### Description ###

This has been tried and obviously it has not been  accepted by a majority of contributors.

**Comment by abucodonosor** [comment]
+1

**Comment by tpgxyz** [comment]
I'm using issues for project tracking. If you do not want to use github issues then please do not use it.
Second in distro-release there is set BUG_REPORT_URL to https://github.com/OpenMandrivaAssociation/distro-release/blob/9edf47c0407a6cd68d5639bd3ce84c05d0dffb3c/distro-release.spec#L15

**Comment by abucodonosor** [comment]
But you bypass QA and everyone with this.

The thing is you DO NOT just track. You are throwing random things into cooker no-one is aware of or decided to be implemented. IF you want to track for your personal use so be it but NOTHING in here should be 'just thrown' in because you like to do that.

**Comment by tpgxyz** [comment]
@abucodonosor great response time. So where QA and everyone is keeping track of ideas ? Please show me this working tool.
