### ISSUE TITLE
Improve entropy generation

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#40]
I think we should decide which entropy generator we should use.

Now we use [rng-tools](https://github.com/nhorman/rng-tools) by default.
I think we should change it to one of below:

- [haveged](http://www.issihosts.com/haveged/)
- [jitterentropy](http://www.chronox.de/jent.html)

In my opinion we should switch to jitterentropy
More details [here](https://www.whonix.org/wiki/Dev/Entropy)

Implement LRNG in kernel https://github.com/smuellerDD/lrng

**Comment by abucodonosor** [comment]
No-one will solve the current problems, until the kernel, grub will solve the entropy madness and systemd ofc.

Right now if you really want to guarantee entropy you need to enable:

Kernel:
 CONFIG_RANDOM_TRUST_CPU
 CONFIG_RANDOM_TRUST_BOOTLOADER

Packages: rng-tools & haveged ( yes both )

Also, you add jitterentropy support to rng.
 
Here is why:

On laptops or boxes with not much HW to initialize an SW daemon may be fine to solve the problem. Here we still need both ( or optional have rng-tools to do != HW based operations ) bc some HW doesn't have an rng generator they need SW one still.

On big boxes, servers, or boxes with a lot of devices to initialize, the SW implementation is running too late anyway, crng breaks already, therefore we need the kernel options. 

Example of box with lots of devices without kernel options:

```
[    0.000000] random: get_random_bytes called from start_kernel+0x361/0x527 with crng_init=0 <-- broken already
[    4.959580] random: crng init done <-- to late

```

This is a Laptop  without kernel options but with 3 HDD, extra wifi card etc to init:

```
[    0.162508] random: get_random_bytes called from start_kernel+0x361/0x527 with crng_init=0 <-- broken already
[    5.497347] random: crng init done <-- to late

```

Both boxes are running rng-tools & haveged.

**Comment by tpgxyz** [comment]
> CONFIG_RANDOM_TRUST_CPU
This is highly dangerous setting, as I guess nobody trust CPU manufacturers who might installed some hardware backdoors

> CONFIG_RANDOM_TRUST_BOOTLOADER
Imho this may be safe option to enable on x86_64 and aarch64

**Comment by abucodonosor** [comment]
> > CONFIG_RANDOM_TRUST_CPU
> 
> This is highly dangerous setting, as I guess nobody trust CPU manufacturers who might installed some hardware backdoors
> 

You are mistaken what it does, We are already forced to TRUST
the CPU as is, or can you provide me with the source code of any microcode firmware?.

If any CPU Vendors want to inject backdoors they can do so with or without that enabled, we don't have any control of the 'CPU code', For the matter, every BIOS Vendor can do that too without you to ever notice.

So it is not more or less dangerous as using any modern CPU as is.

What this does is to use the hw rng for the random generator what so ever if present, which you use anyway later right?.

> > CONFIG_RANDOM_TRUST_BOOTLOADER
> 
> Imho this may be safe option to enable on x86_64 and aarch64

This actually does not much.

**Comment by tpgxyz** [comment]
> So it is not more or less dangerous as using any modern CPU as is.

So why then help potential foes, by enabling that option. There are plenty of articles to not enable this in kernel. Doubt there are so much paranoid people.

https://en.wikipedia.org/wiki/RDRAND#Reception

Guess this improves situation a lot in kernels > 5.4

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=50ee7529ec4500c88f8664560770a7a1b65db72b

**Comment by tpgxyz** [comment]
I did some deeper digging and it looks like our rng-tools is in good shape, as it tries to use many sources (hwrng, CPU jitter, software).

One question left, should we switch to LRNG?

**Comment by abucodonosor** [comment]
> > So it is not more or less dangerous as using any modern CPU as is.
> 
> So why then help potential foes, by enabling that option. There are plenty of articles to not enable this in kernel. Doubt there are so much paranoid people.
> 
> https://en.wikipedia.org/wiki/RDRAND#Reception
> 

Uhmm there are a lot of paranoid people. The same issue is true for UEFI, BIOS,
<insert random blobb name here>.

You will use the HW generator later on in rng-tools *anyway*, do you trust this data then?:)

A large and paranoid distro as Debian is won't enable that it is so dangerous, right?

```
crazy@ant:~/debian$ grep CONFIG_RANDOM_TRUST_CPU debian/config/config
CONFIG_RANDOM_TRUST_CPU=y
crazy@ant:~/debian$ ls
debian  linux_5.4.19-1.debian.tar.xz

```

Source: https://packages.debian.org/de/sid/kernel/linux-config-5.4


> Guess this improves situation a lot in kernels > 5.4
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=50ee7529ec4500c88f8664560770a7a1b65db72b

Not really, there is not a real solution right now, just workarounds.

**Comment by abucodonosor** [comment]
> One question left, should we switch to LRNG?

Why would you do that?. It solves nothing over the current situation and there are reasons why this is still since 2016 and out-of-tree-patchset.

**Comment by tpgxyz** [comment]
Latest kernel-release-clang

```
[root@tpg-virtualbox tpg]# dmesg | grep random
[czw lut 20 15:01:02 2020] random: crng done (trusting CPU's manufacturer)
[czw lut 20 15:01:06 2020] systemd[1]: Initializing machine ID from random generator.
```

**Comment by tpgxyz** [comment]
Done
