### ISSUE TITLE
What the eff is this?

### ISSUE THREAD

**Issue by abucodonosor** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#41]
We do have Bugzilla, @tpgxyz why are you continuing using this?

**Comment by benbullard79** [comment]
Yeah, this is a problem having issues in different places. To difficult to keep up with. Somehow, someway, we absolutely have to get everyone communicating in the same place or places.

I thought we had more than once stated in TC-meetings that Github issue was for things that apply to developers only like specifics of how to write code and things like that. Issues that affect users and well everyone still should be reported at issues.openmandriva.org.

Also fedya has somewhere in Github that ABF guys prefer to have ABF issues reported to. I think under docker.

The point is we all need to do this the same way or problems and conflict will ensue.

**Comment by benbullard79** [comment]
https://github.com/OpenMandrivaAssociation/distro-release/blob/9edf47c0407a6cd68d5639bd3ce84c05d0dffb3c/distro-release.spec#L15

**Comment by tpgxyz** [comment]
@abucodonosor  I'm using this to gather and track new ideas for new releases.

**Comment by omakuta** [comment]
test, to be ignored

**Comment by benbullard79** [comment]
I don't see why we can't close this one.
