### ISSUE TITLE
service cannot be enabled if sysv init script is present

### ISSUE THREAD

**Issue by sash-kan** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#51]
#### Please go to https://issues.openmandriva.org if you want to report any problem or feature.

since registration does not work (https://forum.openmandriva.org/t/cant-register-on-https-issues-openmandriva-org/3689/) i write here.

# Issue Report #

### OpenMandriva Version ###

```
$ cat /etc/os-release
NAME="OpenMandriva Lx"
VERSION="4.1 (Mercury)"
ID="openmandriva"
VERSION_ID="4.1"
BUILD_ID="20200131.11"
PRETTY_NAME="OpenMandriva Lx 4.1 (Mercury)"
VERSION_CODENAME="(Mercury)"
ANSI_COLOR="1;43"
CPE_NAME="cpe:/o:openmandriva:openmandriva_lx:4.1"
HOME_URL="http://openmandriva.org/"
BUG_REPORT_URL="http://issues.openmandriva.org/"
SUPPORT_URL="https://forum.openmandriva.org"
PRIVACY_POLICY_URL="https://www.openmandriva.org/tos"
```

### Description ###

if the package contains a sysv init script, the service cannot be enabled:
```
$ sudo systemctl enable example
example.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable example
failed to glob pattern /etc/rc0.d/[SK][0-9][0-9]example: No such file or directory
```
example script:
```
$ cat /etc/init.d/example
#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

name=$(basename $0)

case "$1" in
    start)
    echo "start ok"
    ;;
    stop)
    echo "stop ok"
    ;;
    restart)
    $0 stop
    $0 start
    ;;
    status)
    echo "status ok"
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
```
the error occurs even if there is a systemd script with the same name.

the error was caused by the _chkconfig_ package (`/lib/systemd/systemd-sysv-install` is symlink to `/usr/sbin/chkconfig`):
1. `chkconfig.spec` contains the command:
   ```
   for n in 0 1 2 3 4 5 6; do
       mkdir -p %{buildroot}%{_sysconfdir}/rc.d/rc${n}.d
   done
   ```
   which is used to create directories `/etc/rc.d/rc[0-6].d`
1. but in the source code of the program itself there is a reference to directories `/etc/rc[0-6].d`. for example:
   ```
   $ grep rc.d chkconfig-1.11/leveldb.c 
       rc = asprintf(&match, "%s/rc%d.d/[SK][0-9][0-9]%s", RUNLEVELS, level, name);
       sprintf(linkname, "%s/rc%d.d/%c%02d%s", RUNLEVELS, level, on ? 'S' : 'K',
   $ grep RUNLEVELS chkconfig-1.11/leveldb.h
   #define RUNLEVELS "/etc"
   ```
which is easy to check:
```
$ sudo ln -s /etc/rc.d/rc0.d /etc/rc0.d
$ sudo ln -s /etc/rc.d/rc1.d /etc/rc1.d
$ sudo ln -s /etc/rc.d/rc2.d /etc/rc2.d
$ sudo ln -s /etc/rc.d/rc3.d /etc/rc3.d
$ sudo ln -s /etc/rc.d/rc4.d /etc/rc4.d
$ sudo ln -s /etc/rc.d/rc5.d /etc/rc5.d
$ sudo ln -s /etc/rc.d/rc6.d /etc/rc6.d
$ sudo systemctl enable example
example.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable example
$ echo $?
0
```
# how do you fix this?
1. (probably a bad way) fix the spec file to create directories `/etc/rc[0-6].d`
1. (probably a good way) fix the source code so that all references are to directories `/etc/rc.d/rc[0-6].d`

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/cant-register-on-https-issues-openmandriva-org/3689/6

**Comment by tpgxyz** [comment]
Thanks for the report, ill take a look on it.

**Comment by tpgxyz** [comment]
@sash-kan fixed for cooker and rolling

**Comment by sash-kan** [comment]
thank you. are there any plans for version 4.1?

**Comment by tpgxyz** [comment]
@sash-kan i've pushed builds for 4.0 and 4.1. If builds will not fail, then you can find updated chkconfig in main/testing repository. Make sure to enable it.

https://abf.openmandriva.org/openmandriva/chkconfig/build_lists#?page=1&per_page=25&ownership=everything

**Comment by tpgxyz** [comment]
Fixed
